### ISSUE TITLE
Target cleanup

### ISSUE THREAD

**Issue by Adeynack** [Adeynack/kotti#24]
To allow as much projects as possible to depend on `kotti`, we should target the default JDK 1.6. This is especially important in order to target "older" Android platforms.

# Tasks
- [x] Target 1.6 instead of 1.8
- [x] Remove all "garbage" in the `build.gradle` files.
- [ ] Create modules for 1.8 (ie: `kotti-core-jdk8`) if needed
- [x] `kotti-core` could depend on the kotti for jdk8 dependency only for tests (to tests things against streams, per instance)
- [ ] Decide and act on deleting the actual published v`0.1` in BinTray.
